### ISSUE TITLE
Improve riotjs tags to be more modular

### ISSUE THREAD

**Issue by overshard** [overshard/timestrap#1]
Just have one giant tag per page that could be much more modular since many of them share components

**Comment by overshard** [comment]
I believe @cdubz wants to handle this, he already made a huge update to timesheets that can be repeated for tasks and entries. We also need to split out pagination since it's the exact same on all our pages.

**Comment by cdubz** [comment]
Sure thing. I will pick this up tonight/tomorrow.

**Comment by overshard** [comment]
This is going to be a constant job, cdubz has done a good job at making what we have more modular and we'll keep doing that as we go.
