### ISSUE TITLE
Review Show HN and create Issues based on comments

### ISSUE THREAD

**Issue by overshard** [overshard/timestrap#10]
Going to review all HN comments and see how people suggest we improve our current direction: https://news.ycombinator.com/item?id=14180673

**Comment by f31n** [comment]
hi, i just found your post on HN.
as other people mentioned why build something thats already there, maybe you wanna check out https://github.com/InvoicePlane/InvoicePlane its great at invoicing / quotes etc etc and of course self hosted ;) 

It would be great to find a way to work together with them (the code is written in php).

One thing i'd really love to see is multi client possibility (you could also create for each company a own instance .. but mäh) so you'd need only one host to serve multiple clients.

**Comment by overshard** [comment]
@f31n I'd prefer this to be as easy as possible to setup and use and I think integrating with a third party invoicing software goes against that for the default settings especially since the third party software in question uses a completely different tech stack. However, as something in the distant future, I would like to support third party options like InvoicePlane if someone doesn't like how we manage invoices and would prefer to export time to another application.
