### ISSUE TITLE
Home and Timesheets pages taking 20 seconds, no data yet

### ISSUE THREAD

**Issue by mikedilger** [overshard/timestrap#11]
I installed locally.  Proxying behind nginx.  Page access line is printed near-enough to immediately.  Most links are fast but Home and Timesheets are dreadfully slow.  I think something is timing out?

**Comment by mikedilger** [comment]
Nevermind.  Seems it "got over it"... after multiple (more than 2) loads of the page.

**Comment by aniljava** [comment]
Reopening this one. 

So far was able to get this. But if there are other debug flags to turn on, please guide. 
![1493053425](https://cloud.githubusercontent.com/assets/412569/25349109/d75aee72-28dd-11e7-965e-32350acfa830.jpg)
