### ISSUE TITLE
Demo is down?

### ISSUE THREAD

**Issue by JaimeObregon** [overshard/timestrap#119]
[timestrap.herokuapp.com](https://timestrap.herokuapp.com/) seems broken (`Server Error (500)`).

**Comment by overshard** [comment]
It is indeed down! Not sure why I didn't get a notice, I'll check it out tomorrow, thanks for letting me know.

**Comment by overshard** [comment]
This should be fixed now, @cdubz was in the process of adding new "sites" functionality and we were having some issues with initial data.
