### ISSUE TITLE
User permissions supporting a read-only user

### ISSUE THREAD

**Issue by mikedilger** [overshard/timestrap#12]
I created a 2nd user with 'staff' status so they could login.  Without any grants it seems they can do most everything (except the admin panel, but all entries are outside the admin panel).

Just registering my interest in the ability to have a read-only user.

**Comment by overshard** [comment]
I think this would be useful for invoicing too if we want to show clients timesheets, they can have their own user with specific timesheet access.

**Comment by cdubz** [comment]
I am working on this a bit. We will use Django's permissions system with REST Framework's integration for now. We just need to sort out where/how to handle 403 responses gracefully.

**Comment by cdubz** [comment]
I have this working at the API level. However, I'm not sure how to get Django user and/or permissions data in to riotjs tags (to prevent display of certain DOM nodes, etc.). This could perhaps be handled at the Views level? I toyed with this a bit but had trouble. @overshard, any thoughts?

**Comment by overshard** [comment]
We probably need to just include the user type in the templates for now. In the future we want to build the user type into the API too for standalone apps, is_staff is already a function but we need to also have is_readonly and if is_staff and is_readonly are both false then it is just your normal user.
