### ISSUE TITLE
Timesheet and Task Completion

### ISSUE THREAD

**Issue by mikedilger** [overshard/timestrap#13]
Once a task is complete, it would be nice to check it off.  Else the list of tasks in the dropdown would grow without end.

**Comment by overshard** [comment]
Should be able to mark timesheets as completed too. Completely agree, this is also part of the step for Invoicing as we need to mark what to invoice.

**Comment by overshard** [comment]
I have swapped this over to an "Archive" system with the new Client > Project organization. If something is marked as "Archive" it no longer shows up on the interface, it still shows up on the admin though in case it needs to be re-enabled.
