### ISSUE TITLE
Demo credentials not working

### ISSUE THREAD

**Issue by bruj0** [overshard/timestrap#133]
The demo at https://timestrap.herokuapp.com/login/ gives an error when using admin/admin as credentials.

**Comment by cdubz** [comment]
@overshard will need to take a look at this. It appears that the `migrate` command was not run with the last deployment. I did just test with the Heroku deploy button and it works fine, so possible some sort of cache issue with that auto-deploy voodoo.

**Comment by overshard** [comment]
This should be fixed now, thank you for reporting it @bruj0 !
