### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by StianOvrevage** [overshard/timestrap#134]
I'm trying to get timestrap to run in Docker but right now it hangs during migration:

```
  Applying core.0003_auto_20171001_1018... OK
  Applying sessions.0001_initial... OK
```
Dockerfile:

```
# docker build --tag timestrap -f Dockerfile .
# 
# docker run -p 8000:8000 timestrap
# docker run -p 8000:8000 -i -t timestrap bash
# 
# /timestrap/db.sqlite3

FROM alpine:3.7

RUN apk add --no-cache python3 && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
    rm -r /root/.cache

RUN apk add --no-cache bash git postgresql-dev build-base python3-dev
RUN pip install pipenv
RUN git clone https://github.com/overshard/timestrap

COPY entrypoint.sh /entrypoint.sh

WORKDIR "timestrap"

RUN pipenv install

# To run pipenv from inside container:
# export SHELL=/bin/sh && pipenv shell

EXPOSE 8000

CMD ["/bin/sh", "-c", "/entrypoint.sh"]
```

entrypoint.sh:

```
cd /timestrap
pipenv run python manage.py migrate --noinput
pipenv run python manage.py runserver
```

Running entrypoint.sh from within the container interactively successfully starts the server:

```
  Applying core.0003_auto_20171001_1018... OK
  Applying sessions.0001_initial... OK
Performing system checks...

System check identified no issues (0 silenced).
December 05, 2017 - 23:49:33
Django version 2.0, using settings 'timestrap.settings.development'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

On another note, it would also be helpfull to be able to configure the database to use somehow. I'm not familiar with Django and how to extend the code to support for example a MySQL database. It would be nice to be able to configure that with for example some env-vars.

**Comment by overshard** [comment]
Hey, thanks for posting this, I do plan on supporting Docker as one of the primary forms of deployment.

To me this looks like it's actually completing the migration just fine and then starting the server, the current issue is that you're not building the static files, the docs do say that this isn't required but that's not 100% true yet, it was at one point and that was removed since we are making it cleaner when we start to do releases.

If you set this up to install node 8 + gulp-cli and run `npm install && gulp build` I think this may work. You can setup custom settings files and support for different databases in the settings folder:

https://github.com/overshard/timestrap/tree/master/timestrap/settings

For an example of a more production ready file check out the Heroku one in there.  For examples of different database configurations you can see Django's docs:

https://docs.djangoproject.com/en/1.11/ref/settings/#databases

We also call the Heroku settings using an envrionmental variable that is added to the Heroku ENV on creation:

https://github.com/overshard/timestrap/blob/master/app.json#L22

What you have here is a great start and I'll see if I can incorporate this sometime later this week/early next week into timestrap itself so you don't have to do any of this research if you don't want to, however, if you do and want to do a PR I'd definitely check it out!

**Comment by cdubz** [comment]
@overshard - Check out the Baby Buddy [Dockerfile](https://github.com/cdubz/babybuddy/blob/master/Dockerfile) if you need some information re: building assets in Docker. I'm not convinced this is the best way to do it, but it gets the job done (with help from docker-compose) in my case.

**Comment by StianOvrevage** [comment]
Ok, so I have it working now!

There is a few workarounds/extra steps that can be removed if fixed upstream:
1. The version of node-sass which is pinned is no longer available and breaks npm install.
2. The entrypoint scripts moves the sqlite database into a database/ subfolder and symlinks it back to the root-project-folder. This so you can volume-mount the database-folder to a folder on the Docker host machine (`docker run -v host-folder:/timestrap/database timestrap`). Hard to do with a file that might be created/initialized in a folder full of other files. Would be better to have the sqlite-file in a database/ subfolder by default.

The image is still relatively big at 189MB. There is 241MB of files inside the image, the majority in these folders:

```
147 MB     /root/.local/share/virtualenvs/timestrap-29kIw6ur
 70 MB     /usr/lib/python3.6
  7 MB     /timestrap
```
Not sure if it's possible to reduce further, or if it's worth the effort.

Anyways, here are the latest files:

Dockerfile:

```
# Build images:
# docker build --tag timestrap -f Dockerfile .
# 
# Run image, listen on port 8000, use db.sqlite3 from same folder:
# docker run -v ./database/:/timestrap/database/ -p 8000:8000 timestrap
#
# Run interactively, for debugging and development:
# docker run -v ./database/:/timestrap/database/ -p 8000:8000 -i -t timestrap bash
# 

# Static file build step
FROM node:9.2-alpine as build

RUN apk add --no-cache git && \
    git clone https://github.com/overshard/timestrap

WORKDIR "/timestrap"

### Bump node-sass to latest version (default is no longer available)
RUN npm install --save node-sass@4.7.2

RUN npm install && \
    npm install -g gulp-cli && \
    gulp build

### Cleanup files no longer needed to reduce image size:
RUN rm -rf /timestrap/node_modules/

# Application build step
FROM alpine:3.7

COPY --from=build /timestrap /timestrap

WORKDIR "/timestrap"

RUN apk add --no-cache python3 && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
    rm -r /root/.cache

RUN apk add --no-cache bash postgresql-dev build-base python3-dev libffi-dev && \
    pip install pipenv && \
    pipenv install && \
    apk del postgresql-dev build-base python3-dev libffi-dev && \
    rm -rf /root/.cache/pip

COPY entrypoint.sh /entrypoint.sh

EXPOSE 8000

CMD ["/bin/sh", "-c", "/entrypoint.sh"]
```

entrypoint.sh:

```
cd /timestrap

echo "Starting database migrations"
pipenv run python manage.py migrate --noinput

echo "Moving database file into database/ subfolder"
mv db.sqlite3 database/
ln -s database/db.sqlite3 db.sqlite3

echo "Starting server"
pipenv run python manage.py runserver 0.0.0.0:8000
```

**Comment by adrum** [comment]
Any progress on this? I can wrap this up in a pull request if needed.

**Comment by overshard** [comment]
Thanks for reminding me! I'm booting up a server and checking on this now.

**Comment by overshard** [comment]
This is almost done, I seem to be running into an issue where the static files aren't being copied from the build step in a multi-stage docker build, specifically: https://github.com/overshard/timestrap/blob/master/Dockerfile#L21

If I can figure out what I'm missing here the rest should be easy!

**Comment by StianOvrevage** [comment]
Try this:

`COPY --from=build . /app/`

**Comment by overshard** [comment]
I'm just trying to get the static files from the build container though, I don't want to copy everything from it

**Comment by cdubz** [comment]
Like so? - https://github.com/cdubz/babybuddy/blob/01868fe2491859981d1dbd47640e30ffdee06153/Dockerfile#L29

**Comment by overshard** [comment]
@cdubz Yeah I think what I have is exactly what you have but mine doesn't seem to be working at the moment. I'll have to debug it tomorrow.

**Comment by overshard** [comment]
This should work now, there's some cleanup to do on the docker settings but it works! Thanks to @cdubz and @StianOvrevage for the help on this, I've stolen ideas from both.
