### ISSUE TITLE
More information about possible use cases

### ISSUE THREAD

**Issue by ageis** [overshard/timestrap#136]
Hey @overshard. Nice app you've got here. "time tracking" is a little vague to me. I'm trying to imagine example use cases. Do you think it would be useful to tell about what this is for or add something to a Wiki page beyond the README.md? It's a little unclear; is it for contractors who want to track how much time they spent on specific tasks so they can invoice properly?

**Comment by overshard** [comment]
You're right there is no real "who is this for" section. I'll definitely add one. My general though on it is that it's for people like me who do work for a variety of companies to keep track of my time spent on each of them and what project that time was spent on. This could be an individual freelancer or something like a marketing company that may have many clients.

I'm going to leave this open so I can think about it and definitely add this to the readme/docs.

**Comment by overshard** [comment]
Added https://docs.gettimestrap.com/uses/ to the docs
