### ISSUE TITLE
Toggl

### ISSUE THREAD

**Issue by cdubz** [overshard/timestrap#147]
[Toggl](https://www.toggl.com/) may be worth taking a look at (if you haven't already). I found my wife using it and was just poking around. Timestrap seems (to me at least) to look and feel a lot better.

**Comment by overshard** [comment]
I do like how clean it is, I'll create an account and poke around a bit!

**Comment by overshard** [comment]
After messing with Toggl for a bit it seems somewhat confusing, in how it functions. I think they are going for too many features to satisfy too many people. I wish to stay away from that happening and keep timestrap as simple as possible.

Something I took away from exploring this is that icons are confusing. I had to try and figure out what their icons mean most of the time and I probably need to do something about that on Timestrap in the future/try not to rely on just an icon and expect people to know what that means.
