### ISSUE TITLE
Improve UX around adding time retroactivelly

### ISSUE THREAD

**Issue by enric1994** [overshard/timestrap#148]
It would be great to have an option to add a retroactive task that you did in the past but you didn't log.

Example:
It's 5pm and you spent the last 2 hours in task X. But you don't click the "Start" button!
I would like to add the time of that task X manually.

Thanks!

**Comment by overshard** [comment]
This is actually already possible, maybe it's not obvious and we should make it more so. If you just put fill in the fields and add a time it will change the "Start" button to an "Add" button and you can just add the time directly. I'll see what I can do about improving the design.

**Comment by gfdsa** [comment]
A date selector the would be a really nice to have too!

**Comment by overshard** [comment]
I agree with this one, I had it at one point and removed it due to design updates, I will work on re-adding the date selector.

**Comment by enric1994** [comment]
Thanks guys! I can add time retroactively now. The UX design is not an easy task!

**Comment by overshard** [comment]
I'm going to leave this open as a reminder to fix the UX of this and add a date picker, if anyone has any suggestions or wants to do a PR to improve this please go ahead!
