### ISSUE TITLE
Running behind reverse proxy with TLS leads to 'Mixed Content' errors

### ISSUE THREAD

**Issue by alecdwm** [overshard/timestrap#149]
Hi there!
Thanks for building such a useful tool!

However, I was hoping to get some help in fixing an issue specific to my environment.  
I'm running timestrap behind an nginx proxy so that nginx can handle the TLS.

Most of the app still works, but specific tasks like updating entries from the timesheet page are broken.  
It would seem this is because the API returns http-specific urls in some responses, which the frontend then uses for future requests.

For example, a request to `https://example.org/api/entries/?user=2` will return an array of results, the `url` parameter of which will look like:

    http://example.org/api/entries/1/

When instead I think it should be:

    //example.org/api/entries/1/

The latter of which would automatically resolve to http(s) based on what the frontend was served via.

I had a look around the python codebase but couldn't find any obvious reference to the code which constructs these urls. It does however seem to be the case that they're stored along with the rest of the entry in the db.  
Any ideas?

**Comment by overshard** [comment]
I'll add something to the README about this but it's not really an issue with timestrap but how django-rest-framework handles TLS behind a reverse proxy. Essentially you need to configure this setting:

https://docs.djangoproject.com/en/2.0/ref/settings/#secure-proxy-ssl-header
