### ISSUE TITLE
How do you give a new user access to clients/projects?

### ISSUE THREAD

**Issue by unformatt** [overshard/timestrap#161]
![image](https://user-images.githubusercontent.com/157132/42285040-4c50fc94-7f7c-11e8-8759-22d3feff5440.png)

**Comment by overshard** [comment]
Added in c65f559

**Comment by unformatt** [comment]
I think this would give the user access to all projects. Is there a way to specify which projects a user can access?

**Comment by overshard** [comment]
No, there are no project or client specific permissions at this time and I don't plan on implementing those. If you wish to separate out a timestrap instance into projects/clients for users you can use the Multiple Sites configuration https://github.com/overshard/timestrap#sites
