### ISSUE TITLE
Why is instance's URL passed to server/API rather than ID?

### ISSUE THREAD

**Issue by unformatt** [overshard/timestrap#163]
Is this DRF convention? I've always passed ID from client to server when referring to an instance of a model with DRF.

From tests.py, `url`is used instead of e.g. `projects[0]['id']`
```python
self.c.post('/api/entries/', {
    'project': projects[0]['url'],
    'user': users[0]['url'],
    'duration': '1:30:00'
})
```

If I want to pre-process any data in the ViewSet, then I'm dealing with e.g. `"http://127.0.0.1:8000/api/projects/1/"` which has to be resolved rather than int `1` which can directly used with model filter.

For example:

```python
def create(self, request):
    project = request.data['project'] # e.g. "http://127.0.0.1:8000/api/projects/1/"
    # TODO: Validate something about project but how to I resolve project URL to model instance?
```

**Comment by overshard** [comment]
This is a default of DRF. You should be using the serializer if you wish to change the way something in the API is being created, deleted, updated, etc and this is all abstracted:

> http://www.django-rest-framework.org/api-guide/serializers/#saving-instances
