### ISSUE TITLE
Websocket issues with admin backend and Time Entry frontend

### ISSUE THREAD

**Issue by zsiddiqi** [overshard/timestrap#164]
Using the latest master branch, built docker containers. Encounter the following exception every time I try to clock a new time entry:

`timestrap-web | Traceback (most recent call last):
timestrap-web |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/asyncioreactor.py", line 267, in run
timestrap-web |     self._asyncioEventloop.run_forever()
timestrap-web |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 523, in run_forever
timestrap-web |     self._run_once()
timestrap-web |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1758, in _run_once
timestrap-web |     handle._run()
timestrap-web |   File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
timestrap-web |     self._context.run(self._callback, *self._args)
timestrap-web | --- <exception caught here> ---
timestrap-web |   File "/usr/local/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
timestrap-web |     return callWithContext({"system": lp}, func, *args, **kw)
timestrap-web |   File "/usr/local/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
timestrap-web |     return context.call({ILogContext: newCtx}, func, *args, **kw)
timestrap-web |   File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
timestrap-web |     return self.currentContext().callWithContext(ctx, func, *args, **kw)
timestrap-web |   File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
timestrap-web |     return func(*args,**kw)
timestrap-web |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/asyncioreactor.py", line 141, in _readOrWrite
timestrap-web |     self._disconnectSelectable(selectable, why, read)
timestrap-web |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 255, in _disconnectSelectable
timestrap-web |     selectable.connectionLost(f)
timestrap-web |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/tcp.py", line 289, in connectionLost
timestrap-web |     protocol.connectionLost(reason)
timestrap-web |   File "/usr/local/lib/python3.7/site-packages/twisted/web/http.py", line 2294, in connectionLost
timestrap-web |     request.connectionLost(reason)
timestrap-web |   File "/usr/local/lib/python3.7/site-packages/daphne/http_protocol.py", line 183, in connectionLost
timestrap-web |     logger.debug("HTTP disconnect for %s", self.client_addr)
timestrap-web | builtins.AttributeError: 'WebRequest' object has no attribute 'client_addr'`

**Comment by overshard** [comment]
Thanks for finding this! I'll check into it when I get some time this weekend.

**Comment by overshard** [comment]
Fixed in the latest update! Sorry for the delay.
