### ISSUE TITLE
All forms need form validation

### ISSUE THREAD

**Issue by overshard** [overshard/timestrap#169]
Currently just getting errors on things like the tracker when a time is submitted with no task + project

**Comment by underdoeg** [comment]
This PR adds a feature that disables the add button in the tracker if no project or task is selected. https://github.com/overshard/timestrap/pull/184

This is an easy to implement approach that doesn't need a ton of error handling

**Comment by overshard** [comment]
That's a solid approach here, need to add the same to the edit form.
