### ISSUE TITLE
Binding on localhost:8000 only. How do I specify 0.0.0.0:8000

### ISSUE THREAD

**Issue by nodesocket** [overshard/timestrap#17]
Seems to bind on localhost by default. What is needed to be changed to bind on `0.0.0.0` _(all interfaces)_?

**Comment by overshard** [comment]
https://docs.djangoproject.com/en/1.11/ref/django-admin/#runserver

You can just run:

    python manage.py runserver 0.0.0.0:8000 (or any port)
