### ISSUE TITLE
add Costs per time

### ISSUE THREAD

**Issue by petrk94** [overshard/timestrap#176]
Hello,

I would like to recommend a feature. Im currently using an Android App for this, but it doesnt has a web version, I would like to use timestrap, but Im missing one feature: getting the total costs for the time I worked.

As example: I have a project where I get 25$ per hour. So if I work 3 hours, I wish to see 75$  in the project report/task and combined. This were pretty great, due I could provide my client a detailed view of the costs.

Does this where possible to implement?
Thanks

**Comment by overshard** [comment]
This is already possible via reports. You can filter by "project" and see the total time spent on that project at the bottom.

**Comment by petrk94** [comment]
You dont understand what I mean, I dont talk about the total time consumption.
Im talking about automated calculating price for the total hour. I dont see this function.

If I set for a project 25$/h, than I would like to see in report page 75$ = 3h etc.

**Comment by overshard** [comment]
Are you talking about providing estimates built into Timestrap? So this wouldn't be time that has been done it is time to be done in the future?

**Comment by petrk94** [comment]
Im sorry, I dont understand you.

I mean, in the report it shows the total time, but I want even see the amount of money I have earned while working on it.

**Comment by Romanmir** [comment]
I'd like to submit an idea for this as well. Perhaps the "Cost per unit" could be configured as part of the "Client" object. That way each Client could be individually configured. Perhaps there could also be a feature that allows for a Global rate. Then, in the report it could show the total cost per job/day/report.

**Comment by overshard** [comment]
@Romanmir I can agree with this, right now it's overly simplified and in some use cases you have different rates for different clients. Reporting also needs to be much stronger so you can generate many more types of reports.
