### ISSUE TITLE
Request: add address for Client for distance calculations.

### ISSUE THREAD

**Issue by Romanmir** [overshard/timestrap#179]
I'd like to submit a request to be able to add an address, or perhaps multiple addresses per Client. This could be further extended to track mileage costs/distances.

**Comment by overshard** [comment]
This should probably be more generalized into "Expense Tracking" since that is just an expense in most cases yes? Or do you need specific milage tracking?

**Comment by Romanmir** [comment]
My specific use case is reporting the mileage for tax purposes. But I don't (currently) charge customers for mileage, but I suppose that could change in the future (or be different for other users). My though was: In settings define a starting address, then for each client, you could define multiple locations, Then when entering the task, you'd need to select the client, and if multiple locations exist, the location.

Then on the report it would, for each job, give the number of miles between the start and end locations.

**Comment by overshard** [comment]
I understand, that makes sense.
