### ISSUE TITLE
How do you backup docker instance?

### ISSUE THREAD

**Issue by finzzz** [overshard/timestrap#187]
If I want to move docker instance from one machine to another, how to do that? Or when I want to backup the data periodically..

**Comment by overshard** [comment]
Hey this is a good question and should be documented. I believe there are a few ways, the easiest might be to use docker export and docker import:

https://docs.docker.com/engine/reference/commandline/export/
https://docs.docker.com/engine/reference/commandline/import/

All of our data is stored in the "db" container in the "/db-data" folder and "db" volume. Exporting the db container will also export the data.

I have not tested this yet and need to and will update this on what I find.
