### ISSUE TITLE
Can't create tasks or entries if timesheet has name with unicode characters

### ISSUE THREAD

**Issue by ati** [overshard/timestrap#20]
E.g. "Юникод", russian for "Unicode" timesheet gives "Server Error (500)" page when I try to create a task.

**Comment by overshard** [comment]
Thank you for testing this. With Python 2 unicode is always a pain, I suspect when I have full support for Python 3 then it won't have an issue. I'll look into including tests and making sure I support Python 2 unicode though as I do want to support a variety of languages.

**Comment by mikedilger** [comment]
I installed it initially in a virtualenv with python2.  Then I did it again with python3.  It seemed to work either way.

**Comment by overshard** [comment]
Thanks for checking that out @mikedilger , I've went ahead and setup Travis-CI to test with the most recent 3 major releases of python 3.x along with python 2.7 and it seems to be working great! Still need to fix unicode in Python 2.7 though.

**Comment by overshard** [comment]
I've tested this and everything seems to be working now. Not sure what change fixed this but I've added some starting tests for unicode and we don't get errors anymore! Marking this part as done but going to open a new issue about supporting translations to languages like Russian.

**Comment by overshard** [comment]
Reopening this, I noticed that the django-rest-framework browser bugs out with unicode, our interface works fine. I looked into it some but have not found a solution for the django-rest-framework browser.

**Comment by overshard** [comment]
This has been actually fixed now with the latest updates!
