### ISSUE TITLE
Add Pipenv to project, make sure to include Heroku pre-compile hook

### ISSUE THREAD

**Issue by esikachev** [overshard/timestrap#21]
You can add tox.ini file for more convenient working with virtual environments.

Source: https://tox.readthedocs.io/en/latest/

If you wish, I can work on it

**Comment by overshard** [comment]
We do need something like this to handle different requirements for different environments. I'm honestly not sure what the best choice is. I'll play with tox a bit and get back with you.

**Comment by overshard** [comment]
This isn't exactly what I expected honestly, tox is great for testing in multiple virtualenv but that's not what I'm looking for since travis-ci does a good job at catching issues with other python versions. I'm more looking for https://github.com/kennethreitz/pipenv
