### ISSUE TITLE
Handling form insertion for editing

### ISSUE THREAD

**Issue by overshard** [overshard/timestrap#22]
Right now I'm inserting a form via jQuery and it seems very inelegant to me. I can't seem to find the official riot.js way of handling this. If someone has any information on how to better handle inserting edit forms into the rows I'm all ears.

https://github.com/overshard/timestrap/blob/master/core/static/core/tags/timesheets.tag#L98

**Comment by Leahelisabeth** [comment]
@overshard i noticed that when i tried to edit on multiple timesheet items at once, that when i clicked 'save' on when it exited out of both editing forms but did save changes on the one on which i clicked 'save' is this what you are talking about or are you more generally referring o the UI?

**Comment by overshard** [comment]
That is because I'm calling tag.getTimesheets(); and just resetting the whole thing. That's also a problem but that part is easily fixable, we should just update the one element. The problem is just inserting a form here using jQuery. I'm wondering if there is a better way to insert a form, like create a new tag in riot.js and mount it in place of the current element, instead of using jQuery to messily replace the HTML with a form which seems to go against the application design philosophy of Riot.

**Comment by Leahelisabeth** [comment]
@overshard i think this is a great app you all have here and I would be happy to be a regular contributor if you would have me, do you guys have a slack channel going and/or git project cards for listing bug assigns?

**Comment by overshard** [comment]
@Leahelisabeth Don't have anything, I started this by myself on Friday and here I am! If you'd like to contribute you can fork the repo, code something and then do a pull request. If you'd like to contact me to discuss what needs done so we don't step on each other's toes, my email is on my GitHub profile and maybe we can setup something more real time.

**Comment by overshard** [comment]
I've got this mostly figured out now after discussing with a few people I, or someone else, will have a patch to clean it up shortly!

**Comment by whitebook** [comment]
@Leahelisabeth  Im not a riot.js expert, but you might want to look into the Riot.js docs.

I dont think this is right. (using jquery)
(looking at static/core/tags/tasks.tag)

        editTask(e) {
            let task = e.item;
            let tr = e.target.parentElement.parentElement;
            let td = $(tr).find('td');

            if ($(tr).hasClass('editing')) {
                task.name = $(td[0]).find('input').val();
                task.timesheet = $(td[1]).find('select').val();
                quickFetch(task.url, 'put', task).then(function(data) {
                    $(tr).removeClass('editing');
                    $(td[0]).html(data.name);
                    $(td[1]).html(data.timesheet_details.name);
                    $(td[2]).find('.btn-warning').html('Edit');
                });
            } else {
                $(tr).addClass('editing');
                $(td[0]).html('<input type="text" class="form-control form-control-sm" value="' + task.name + '" onkeypress="return event.keyCode != 13;">');

                $('.timesheet-select').chosen('destroy');
                $(td[1]).html($('.timesheet-select').parent().html());
                $(td[1]).find('.timesheet-select option[value="' + task.timesheet + '"]').attr('selected', 'selected');
                $('.timesheet-select').chosen();

                $(td[2]).find('.btn-warning').html('Save');
            }
        }



I found some examples that do something similar.
(From this Blog Post http://streamdata.io/blog/exploring-riot-js-part5/)

var userService = new UserAsyncService();

routes.users = function(id, item) {
  mount('loading');
  
  if (id) {
    if (item == 'profile') {
      userService.fetchUserNameAndProfile(id)
        .then(userProfile => {
            mount('user-profile', { user: userProfile });
         });

    } else if (item == 'hobbies') {
      userService.fetchUserNameAndHobbies(id)
        .then(userHobbies => {
            mount('user-hobbies', { user: userHobbies });
        });

    }
  } else {
      userService.fetchUsers()
        .then(users => {
          mount('users-page', {users: users});
        });
  }
}

I will try to submit something more meaningful, but I hope that it gives you some inspiration.

**Comment by overshard** [comment]
Thank you for the additional information @whitebook, this is what I'm trying to work towards! This is kind of what I worked out so far, I've broke the individual row of timesheets out on it's own:

    <timesheet>
        <tr if={ !edit }>
            <td>{ name }</td>
            <td class="text-right">
                <a class="btn btn-warning btn-sm" onclick={ editTimesheet }>Edit</a>
                <a class="btn btn-primary btn-sm" onclick={ goToTasks }>Tasks</a>
                <a class="btn btn-primary btn-sm" onclick={ goToEntries }>Entries</a>
            </td>
        </tr>
        <tr if={ edit }>
            <td>{ name }</td>
            <td><input type="text" class="form-control form-control-sm" value="{ name }" onkeypress="return event.keyCode != 13;">
            <td class="text-right">
                <a class="btn btn-warning btn-sm" onclick={ editTimesheet }>Edit</a>
                <a class="btn btn-primary btn-sm" onclick={ goToTasks }>Tasks</a>
                <a class="btn btn-primary btn-sm" onclick={ goToEntries }>Entries</a>
            </td>
        </tr>


        <script>
            var self = this;
            var edit = false;

            editTimesheet(e) {
                self.edit = true;
                self.update();
            }

            goToTasks(e) {
                document.location.href = tasksUrl + e.item.id;
            }


            goToEntries(e) {
                document.location.href = entriesUrl + e.item.id;
            }
        </script>
    </timesheet>

And you can iterate over a custom tag in riot.js:

    <timesheet each={ timesheets } data={ this } />

The issue is that it's including the <timesheet></timesheet> tag in a table and messing up everything. To make this work we need to do away with the actual <table></table> and create a table using div tags with CSS display properties.

I'll review what you posted here as well and see how that works out.

**Comment by cdubz** [comment]
Anyone have additional feedback on this approach before I make similar changes to other tags?

**Comment by overshard** [comment]
In light of what @JHSheridan has posted I think we should hold off on doing this for all the templates and consider heading more towards his design vision for this. It makes everything cleaner and solved a problem I had with Timesheets > Tasks organization.

**Comment by cdubz** [comment]
I think it is still worth splitting tags, in general. Even with a design overhaul and potential move to flex box, the tag hierarchy likely wouldn't change. Just the tag names and HTML structure. But happy to also look at other issues if you want to wait.

**Comment by overshard** [comment]
We definitely need to split up tags to make them modular still and if you want to look into the pagination split still that would still be useful as pagination isn't going anywhere. Just going through and reworking things like the task page edit functionality would be a waste.

**Comment by cdubz** [comment]
Sounds good. I'll jump in to pagination this evening.

**Comment by overshard** [comment]
This has been taken care of really well by @cdubz and I'm closing this, we will continue using the implementation he came up with as a basis for future interface updates for now.

**Comment by whitebook** [comment]
I would say we should add some light error handling as well. Entries also has a bug when you add time, the Total does not increase...

**Comment by overshard** [comment]
@whitebook Error handling is definitely on the way, I'm in the middle of recoding the entire entries display, we're still just trying to nail down the basics. The total problem comes down to #3 , that will definitely update once it's complete.
