### ISSUE TITLE
Disable use of third party networks

### ISSUE THREAD

**Issue by aniljava** [overshard/timestrap#24]
Is it possible to turn off use of cloudfare and unpkg.com.

**Comment by overshard** [comment]
It's planned for the future, right now I'm adding and removing so many libraries that including them all in the repo would be a wasted effort. I'll leave this open as a reminder for the 1.0 release to make sure we don't use third parties though.

**Comment by overshard** [comment]
We should probably check into setting up a basic bower file for this? Is there a better alternative that does not require nodejs dependency? (Something more Python...)

**Comment by cdubz** [comment]
Have you looked at [calmjs](https://pypi.python.org/pypi/calmjs)? It still creates a nodejs dependency, but seems a bit more Pythonic. So far I haven't been able to find any non-node alternative, other than directly including libraries.

**Comment by overshard** [comment]
Yeah I can't find a way around the node dependency, clamjs seems pretty cool. We will probably end up using https://yarnpkg.com/en/ I assume which may not be too bad since there are packages built for most operating systems for yarn.

**Comment by cdubz** [comment]
Another potentially useful package to consider: [django-pipeline](https://django-pipeline.readthedocs.io/en/latest/index.html). Not exactly what we are looking for here, but maybe worth a look vs. `django_compressor`, `django-libsass`, and `whitenoise`. Not 100% sure about feature parity but it looks interesting.

**Comment by overshard** [comment]
This has been setup with the use of yarn, all files are now localized
