### ISSUE TITLE
UX: display error that task cannot be added without timesheet

### ISSUE THREAD

**Issue by Leahelisabeth** [overshard/timestrap#25]
I think giving the user a warning rather than nothing happening/no response.
 it is a nice feature that they have on toggl to allow a user to add a task without a timesheet/assigned project then give the option to assign one later, however i just got a failed post in my network tab/console

**Comment by overshard** [comment]
You're absolutely correct, we should definitely have warnings here if an error occurs. (There should be a warning everywhere when errors occur with the API.) This just hasn't been coded yet as I'm trying to get basic functionality up. Leaving this to-do open though because it 100% needs to happen.

**Comment by overshard** [comment]
Fixed this issue by creating a default General task on every Timesheet creation in 2d5294bd5974c79569c4274accf0309936e67cf6
