### ISSUE TITLE
Automate Heroku test server updates

### ISSUE THREAD

**Issue by overshard** [overshard/timestrap#28]
If a Travis build is successful Heroku should automatically be updated

**Comment by mcat-ee** [comment]
Also; although your README.md says the Heroku instance will reset... it definitely doesn't; it appears to have clocked up about 200 entries over the past 5 days.

**Comment by overshard** [comment]
@mcat-ee It's auto generated, every 10 minutes it deletes the entire database and generates random data so people can see an example of what it looks like in use.

**Comment by overshard** [comment]
This should be setup now.
