### ISSUE TITLE
No way to see total time if pagination is invoked

### ISSUE THREAD

**Issue by overshard** [overshard/timestrap#3]
For very long entry lists we resort to pagination and total time just adds entries currently on the page

**Comment by overshard** [comment]
I don't know of a good solution to this one honestly. I don't want to do the total calculation on the front-end and all I can think of is we inject the total time into the serializer. Right now with pagination we have "next", "previous", "count", and "results". The results including all the entires. We could put another element after "count" that is "total_time" for all entries non-paginated and "sub_total_time" which is the time of those currently on the page. This might be messy to implement though, any thoughts on this from anyone else?

**Comment by cdubz** [comment]
Hopefully that wouldn't be too messy, we can write a [custom pagination style](http://www.django-rest-framework.org/api-guide/pagination/#custom-pagination-styles) for rest framework and just do a totaling query there, right? I haven't used rest framework before so I'll have to poke around a bit.

**Comment by overshard** [comment]
Yes, that's my understanding. Just subclass the current pagination and add a couple new items to the response. You have all the data via the data variable.

**Comment by overshard** [comment]
This is done
