### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by overshard** [overshard/timestrap#32]
I'd like to support as many languages as possible and since there won't be much of an interface I feel like translations won't be hard to acquire. We need to make sure we use the https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#lazy-translation and get this running once we are near 1.0 release. I feel like implementing this early might cause too much overhead but if anyone wants to start work on it that's cool!

**Comment by ad-m** [comment]
Tasks to do (and verify):

Need to update
- [ ] models fields to specify ``verbose_name`` for each field using ``ugettext_lazy``,
- [ ] ``Meta`` of models to specify ``verbose_name`` and ``verbose_name_plural`` to each model class using ``ugettext``,
- [ ] ``__str__`` in models to use ``ugettext``,
- [ ] need migrations updated,
- [ ]  ``AppConfig`` in ``apps.py`` for each application to specify  ``verbose_name`` in  using ``ugettext_lazy``,
- [ ] update ``fieldset`` in each ``admin.py`` to use ``ugettext`` using ``ugettext``,
- [ ] update ``actions`` in each ``admin.py`` to define ``short_description`` using ``ugettext``,
- [ ] update dynamic fields in ``list_display`` in each ``admin.py`` to define ``short_description`` using ``ugettext``,
- [ ] update titles (and wrap each text) in ``templates`` in ``trans`` or ``blocktrans``,

I never need to translate JavaScript, so I don't know ways.

**Comment by overshard** [comment]
For javascript strings we will probably just use django's translation system and put the strings at the bottom of the template as variables

**Comment by overshard** [comment]
We can add the translation strings to the bottom of the timestrapConfig that I've setup in the base template and call the string var instead of the name directly to translate in JS situations
