### ISSUE TITLE
Export does not honor filters

### ISSUE THREAD

**Issue by poulpreben** [overshard/timestrap#34]
When exporting a report, all entries in any timesheet, task or date range are exported.

**Comment by overshard** [comment]
Known issue right now, I just moved exports to the Reports page and we have someone working on filtering for exports along with export format types. I'll keep this open till it's fixed in the next few days!

**Comment by overshard** [comment]
@Leahelisabeth is working on this in her current PR #36 , still needs cleaned up a bit though.

**Comment by overshard** [comment]
This was completed by @cdubz based on Leah's previous work
