### ISSUE TITLE
Add integration ID to all models for use in external service relationships

### ISSUE THREAD

**Issue by mikedilger** [overshard/timestrap#48]
I am investigating plugging into my client's task management system (workflowmax.com) and all I really need is a place to store their IDs in timestrap for client, project, and entry, so that I can match up data when I synchronise.  Reference fields would do that nicely.

Low priority.  I probably wont even do the integration because their API looks worse than yours (!)

**Comment by overshard** [comment]
It looks like they have their own time tracking system built in, what are we wanting to integrate here? Just have cross posting of entries between the two so someone can use either of them for tracking time?

**Comment by mikedilger** [comment]
I want to enter into timestrap, and have a script that I write pull new projects from workflowmax (my client assigns them to me) and push new entries into workflowmax (i record my hours).  That way my client is happy and I don't have to enter the data twice (once in my system, once on theirs).

I would do all the work here.  Only thing needed is a generic "external reference id" field so I can match things up.  Such a field would work for anyone wanting to use it, and most people could ignore it, it would be database and api-only (no need to render it).

**Comment by overshard** [comment]
That makes sense, I think an integration ID of some sort could be important for many different services so I'll put this as an enhancement and definitely add it in!

**Comment by overshard** [comment]
I'm probably not going to implement this as it adds a lot of extra complexity for no real gain.
