### ISSUE TITLE
Enter date when adding an entry

### ISSUE THREAD

**Issue by msander** [overshard/timestrap#49]
Thanks for opensourcing this great software.

For using it in production, I'm missing one important feature: Selecting the date of the entry.
Often I forgot to enter the time when I go home in the evening and want to add it on the next day.... Or I'm working on a specific task multiple days and want to track them afterwards.

**Comment by overshard** [comment]
We had this originally and removed it with the redesign. It's supported by going into the admin panel after entering in times and adjusting them via the admin but that doesn't seem very friendly for this use case. I agree it should be on the entries page itself as it is a functionality I use too. We'll see how we can work this in!
