### ISSUE TITLE
Create Makefile for common actions like manage commands, updating, documentation building

### ISSUE THREAD

**Issue by overshard** [overshard/timestrap#50]

**Comment by overshard** [comment]
Holding off on this as it requires crypto packages to be compiled and I don't want to add too many dependencies

**Comment by ad-m** [comment]
Why fabfile? Why not standard Linux ```Makefile```?

**Comment by overshard** [comment]
@ad-m Makefile might work! Since we do have a build-essential/compile dependency so you make a good point, not sure how well that carries over to other operating systems though? I don't have much documentation for windows right now anyways...

**Comment by ad-m** [comment]
@overshard , it's should work nice on Mac OS X I think too. I do not care about Windows for ideological reasons.

**Comment by glujan** [comment]
I'm not sure what kind of commands you want to have but [Tox](https://tox.readthedocs.io) can handle building distributions, docs, running tests (on different Python versions) and other tasks. It works on Windows, macOS and Linux and integrates nicely with CI, too.

It won't substitute commands from `manage.py`, though.

**Comment by overshard** [comment]
Right now we've settled on using Gulp for most command we want to handle. We may implement Tox still just to handle multi environment testing with NVM node 4+6 and multiple versions of python locally.

**Comment by overshard** [comment]
This is complete as of now, we use Gulp for everything
