### ISSUE TITLE
Navigation bar broken

### ISSUE THREAD

**Issue by overshard** [overshard/timestrap#53]
Text doesn't show up till hovered over with new localized css and js

**Comment by cdubz** [comment]
Once I got up and running from HEAD (5991ae6), the navbar is working correctly with - text is there and hover effects are normal.

**Comment by overshard** [comment]
Did you enable compression in the development config? You need to uncomment two lines in there, it's only an issue when compression is enabled.

**Comment by overshard** [comment]
To recreate this right now, since I have a work around, you need to add the following to the development settings:

    COMPRESS_ENABLED = True
    COMPRESS_OFFLINE = False

And then go into the base.html template and move the bootstrap.min.css link tag into the compress block

**Comment by overshard** [comment]
The problem is django-compressor breaks with lined SVGs in CSS url tags which bootstrap v4 makes extensive use of. The latest develop branch fixes this.

**Comment by cdubz** [comment]
I haven't tested this locally, but FYI I do still see it on the [Heroku instance](https://timestrap.herokuapp.com/).

**Comment by overshard** [comment]
It's because I set the egg=django-compressor==2.1.1 so it did not actually recompile the package using the develop branch, I should set it to django-compressor=develop, it is fixed the dependency on heroku just didn't update.
