### ISSUE TITLE
Heroku deployment - Run scripts & scale dynos error

### ISSUE THREAD

**Issue by sohamnavadiya** [overshard/timestrap#66]
When I tried to deploy the first version on Heroku. It was working fine. Now latest version is installing properly.

Below is the error that I am getting in Run scripts & scale dynos section during deployment on heroku.

```
packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "timesheets_entry_task_id_300bf726" already exists
```

**Comment by overshard** [comment]
I seem to be getting the exact same error on our current Heroku instance, thank you for reporting this! I'll take a look at it later tonight.

**Comment by overshard** [comment]
This seems to be an issue with the order migrations are run on PostgreSQL, I'm not 100% sure how to fix this at the moment and will have to do some investigation

**Comment by overshard** [comment]
This may not be easily fixable with postgres so we may have to change up the models a bit here. We might also want to consider adding tests against postgres and not just sqlite after this.

**Comment by overshard** [comment]
This should be fixed with the latest refactor, it seems to be a bad idea to split up models into apps when there is a lot of cross dependency via ForeignKeys

**Comment by sohamnavadiya** [comment]
@overshard Thanks for investigating on this and share what is a bad idea.
