### ISSUE TITLE
Reports filters limited by page size

### ISSUE THREAD

**Issue by cdubz** [overshard/timestrap#68]
The drop-down filters on the Reports page (Users, Clients & Projects) are limited by the `REST_FRAMEWORK.PAGE_SIZE` setting in `timestrap/settings/base.py` - if there are more than 50 of any of those models, only the first 50 will show up in the list.

**Comment by overshard** [comment]
I'm working on this, it just involves turning off pagination by default as we only really need it for entries. I need to refactor the tags though to expect results without the pagination though.

**Comment by cdubz** [comment]
This was addressed during the Vue rewrite.
