### ISSUE TITLE
Have travis auto-build releases with built in static files so nodejs isn't required

### ISSUE THREAD

**Issue by overshard** [overshard/timestrap#78]
I've included the compiled static_src in the project as a way to avoid the Node.js dependency on all systems. Node is only really necessary if you are working with static files in some way. It is normally a bad practice to include these files in a projects repo though. Should we remove them or leave them as is? Leaving this as an open Issue as it has been brought up multiple times.

**Comment by glujan** [comment]
Ideally Travis should build your distribution and create _GitHub releases_ as described in [Travis docs](https://docs.travis-ci.com/user/deployment/releases/).

**Comment by overshard** [comment]
@glujan that probably exactly what we need to do, thanks for bringing this to my attention. We'll definitely get this setup.

**Comment by overshard** [comment]
Removed static files from repo and are building them on the Heroku deploy, going to include them in releases in the future, leaving this open as a reminder to set that up on travis once we start releases

**Comment by overshard** [comment]
Probably not going to do this as there are a lot of issues with Travis at the moment, going to just support using docker for people who don't want to install a bunch of local packages.
