### ISSUE TITLE
Move routes into actual tags they pretain to

### ISSUE THREAD

**Issue by overshard** [overshard/timestrap#81]
Right now all routes reside in app.html template and they should actually be in their individual tags

**Comment by cdubz** [comment]
Are we thinking we want to use [tag-based routing](http://riotjs.com/api/route/#tag-based-routing)? I made a passing effort to look at this earlier but the documentation and examples were really lacking.

**Comment by overshard** [comment]
Nah, we probably don't want to bother with tag based routing, just move the routes into the JS section of the tag they relate to. In the most recent update I at least moved the tags out of the template and into a routes.js file though. We can't fully have a good routes setup though till all pages are apart of the SPA probably.

**Comment by overshard** [comment]
Probably just going to leave these in a routes file as not all tags are called and they won't be initiated because of that.
