### ISSUE TITLE
Python 3: TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by glujan** [overshard/timestrap#87]
I've recently started using your project but there is a bug preventing from running correctly on Python 3.

[This code] is invalid in Python 3. You need to run `obj.email.lower().encode()`. [Travis] told you that :slightly_smiling_face: 

Do you need any help setting up CI to be more reliable?

[This code]: https://github.com/overshard/timestrap/commit/eb069b285f8752b68e719495f9495bd23c13f286#diff-39f8266a93579ae5dbdb3790c2bfda58R24z
[Travis]: https://travis-ci.org/overshard/timestrap/jobs/234613075#L1168

**Comment by cdubz** [comment]
At least half of our tests are broken at the moment after a major refactor a few days ago, hah. Likely this just got overlooked in the spaghetti of errors. I'll take care of it as I address those.

@overshard handles CI so he'll let ya know if he's looking for any help.

**Comment by overshard** [comment]
Thank you for finding this, as cdubz said all of our tests broke with a huge refactor a day or two ago. Our CI is nicely setup and I kept implementing features while tests were broken.

Now that cdubz has fixed the selenium tests we can catch these! Stability will greatly improve once we have a release.

I'm all up for any tips you may have that relate to Travis CI though, it's the first time I've extensively used Travis.
